#!/bin/sh
if ( test $# -eq 1 ) then
	cat fort.7 >> b.$1
	cat fort.8 >> s.$1
	cat fort.9 >> d.$1
	echo "Appending fort.7 to b.$1 ... done"
	echo "Appending fort.8 to s.$1 ... done"
	echo "Appending fort.9 to d.$1 ... done"
elif ( test $# -eq 2 ) then
	cat b.$1 >> b.$2
	cat s.$1 >> s.$2
	cat d.$1 >> d.$2
	echo "Appending b.$1 to b.$2 ... done"
	echo "Appending s.$1 to s.$2 ... done"
	echo "Appending d.$1 to d.$2 ... done"
else
	echo "Illegal command"
fi
