#! /usr/bin/env python

import sys
import os
sys.path.append(os.path.join(os.environ["AUTO_DIR"],"python"))
from AUTOCommands import commandRunnerLoadName

# This is the Python syntax for making a script runnable
if __name__ == '__main__':
    input = sys.argv[1]
    output = sys.argv[1]
    if len(sys.argv) > 2:
        output = sys.argv[2]
    load=commandRunnerLoadName(input)
    c=load().data
    if c.options["homcont"] is not None:
        for k,v in c.options["homcont"].items():
            c.c[k] = v
    c.c.writeFilename('c.'+output,new=True)
    if len(sys.argv) <= 2 and os.path.exists('h.'+sys.argv[1]):
        os.remove('h.'+sys.argv[1])
