#!/bin/sh
cp b.$1 b.$2
cp s.$1 s.$2
cp d.$1 d.$2
cp c.$1 c.$2
echo "Copying b.$1 to b.$2 ... done"
echo "Copying s.$1 to s.$2 ... done"
echo "Copying d.$1 to d.$2 ... done"
echo "Copying c.$1 to c.$2 ... done"
