#!/bin/sh
echo " "
if test -f $1.f -o ! -f $1.c; then
  echo "(Required files : $1.f, c.$1, $1.dat)"
else
  echo "(Required files : $1.c, c.$1, $1.dat)"
fi
echo " "
make -f $AUTO_DIR/cmds/cmds.make fcon EQUATION_NAME=$1
cp c.$1   fort.2
cp $1.dat fort.3
./fcon
mv fort.8 s.dat
rm fcon* fort.2 fort.3
echo " "
echo "Conversion done : converted file saved as s.dat"
