#!/bin/sh
rm -f fort.2
CFILE=
SFILE=
if ( test $# -eq 1 ) then
	CFILE="$1"
	if (test -r s.$1) then
		SFILE="$1"
	fi
elif ( test $# -eq 2 ) then
        if ( test -r c.$1 -a -r s.$2 ) then
	     CFILE="$1"
	     SFILE="$2"
        else
	     CFILE="$1.$2"
	     if (test -r s.$1) then
		SFILE="$1"
	     fi
        fi
elif ( test -r c.$3 -a -r s.$2 ) then
	CFILE="$3"
	SFILE="$2"
else
	CFILE="$1.$2"
	SFILE="$3"
fi
cat h.$CFILE > fort.12
if ( test -n "$SFILE" -a -r c.$CFILE ) then
	echo s=\'$SFILE\' | cat - c.$CFILE | make -f $AUTO_DIR/cmds/cmds.make EQUATION_NAME=$1
else
	make -f $AUTO_DIR/cmds/cmds.make EQUATION_NAME=$1 < c.$CFILE
fi
