#! /usr/bin/env python

import sys
import os
sys.path.append(os.path.join(os.environ["AUTO_DIR"],"python"))
from AUTOclui import *
import parseBandS

# This is the Python syntax for making a script runable    
if __name__ == '__main__':
    if len(sys.argv) > 1:
        code=sys.argv[1]
        if code[0] == '-':
            codes=[code[1:3].upper()]
            n=1
        else:
            codes=None
            n=0
    if len(sys.argv) == n+3:
        changedb='b.'+sys.argv[n+2]
        changeds='s.'+sys.argv[n+2]
        bs=bt(sys.argv[n+1])
    else:
        if len(sys.argv) == n+2:
            changedb='b.'+sys.argv[n+1]
            changeds='s.'+sys.argv[n+1]
        else:
            changedb='fort.7'
            changeds='fort.8'
        origb=changedb+'~'
        origs=changeds+'~'
        try:
            os.remove(origb)
        except:
            pass
        try:
            os.remove(origs)
        except:
            pass
        os.rename(changedb,origb)
        os.rename(changeds,origs)
        if len(sys.argv) == n+2:
            bs=bt(sys.argv[n+1]+'~')
        else:
            bs=parseBandS.parseBandS('fort.7~','fort.8~')
    bs.deleteLabel(codes,keep=1,keepTY=1)
    bs.writeFilename(changedb,changeds)
    print(" @klb: Rewriting finished.")
