#!/bin/sh
if ( test $# -eq 1 ) then
	mv b.$1 fort.27
	mv s.$1 fort.28
	$AUTO_DIR/bin/listlabels
	mv fort.27 b.$1
        mv fort.28 s.$1
else
	mv fort.7 fort.27
        mv fort.8 fort.28
	$AUTO_DIR/bin/listlabels
	mv fort.27 fort.7
        mv fort.28 fort.8
fi
