#! /usr/bin/env python

import sys
import os
sys.path.append(os.path.join(os.environ["AUTO_DIR"],"python"))
import parseB

# This is the Python syntax for making a script runable    
if __name__ == '__main__':
    if len(sys.argv) > 1:
        diagram=parseB.parseB('b.'+sys.argv[1])
    else:
        diagram=parseB.parseB('fort.7')
    diagram.writeScreen()

