#! /usr/bin/env python

import sys
import os
sys.path.append(os.path.join(os.environ["AUTO_DIR"],"python"))
from AUTOCommands import commandMergeBranches

# This is the Python syntax for making a script runnable
if __name__ == '__main__':
    if len(sys.argv) > 2:
        merge = commandMergeBranches(sys.argv[1],sys.argv[2])
    elif len(sys.argv) > 1:
        merge = commandMergeBranches(sys.argv[1])
    else:
        merge = commandMergeBranches()
    merge()
