#!/bin/sh
if ( test $# -eq 1 ) then
	cat c.$1 > fort.2
	if (test -r s.$1) then
		cat s.$1 > fort.3
	fi
	make -f $AUTO_DIR/cmds/cmds.make EQUATION_NAME=$1
elif ( test $# -eq 2 ) then
	cat c.$1 > fort.2
	cat s.$2 > fort.3
	make -f $AUTO_DIR/cmds/cmds.make EQUATION_NAME=$1
else
	cat c.$3 > fort.2
	cat s.$2 > fort.3
	make -f $AUTO_DIR/cmds/cmds.make EQUATION_NAME=$1
fi
