#!/bin/sh
echo " File recovery ... done."
if ( test $# -eq 1 ) then
	mv b.$1 b.tmp
	mv s.$1 s.tmp
	mv b.$1~ b.$1
	mv s.$1~ s.$1
	mv b.tmp b.$1~
	mv s.tmp s.$1~
else
	mv fort.7 tmp.7
	mv fort.8 tmp.8
	mv fort.7~ fort.7
	mv fort.8~ fort.8
	mv tmp.7 fort.7~
	mv tmp.8 fort.8~
fi
echo " File recovery ... done."
