#!/bin/sh
if ( test $# -eq 1 ) then
	mv b.$1 fort.27
	mv s.$1 fort.28
	$AUTO_DIR/bin/reduce
	mv fort.27 b.$1~
        mv fort.28 s.$1~
        if (test -r fort.37) then
		mv fort.37 b.$1 
        fi
        if (test -r fort.38) then
		mv fort.38 s.$1 
		echo " rl: File reduction finished."
        fi
elif( test $# -eq 2 ) then
	mv b.$1 fort.27
	mv s.$1 fort.28
	$AUTO_DIR/bin/reduce
	mv fort.27 b.$1~
        mv fort.28 s.$1~
        if (test -r fort.37) then
		mv fort.37 b.$2 
        fi
        if (test -r fort.38) then
		mv fort.38 s.$2 
		echo " rl: File reduction finished."
        fi
else
	mv fort.7 fort.27
        mv fort.8 fort.28
	$AUTO_DIR/bin/reduce
	mv fort.27 fort.7~ 
        mv fort.28 fort.8~
        if (test -r fort.37) then
		mv fort.37 fort.7
        fi
        if (test -r fort.38) then
		mv fort.38 fort.8
		echo " rl: File reduction finished."
        fi
fi
