#!/bin/sh
if ( test $# -eq 1 ) then
	cp b.$1 fort.27
	cp s.$1 fort.28
	$AUTO_DIR/bin/relabel b.$1 s.$1 b.$1~~ s.$1~~
        if (test -r b.$1~~) then
		mv b.$1 b.$1~
		mv b.$1~~ b.$1 
        fi
        if (test -r s.$1~~) then
		mv s.$1 s.$1~
		mv s.$1~~ s.$1 
		echo " rl: Relabeling finished."
        fi
elif( test $# -eq 2 ) then
	$AUTO_DIR/bin/relabel b.$1 s.$1 b.$2 s.$2
        if (test -r s.$2) then
		echo " rl: Relabeling finished."
        fi
else
	$AUTO_DIR/bin/relabel fort.7 fort.8 fort.37 fort.38
        if (test -r fort.37) then
		mv fort.7 fort.7~
		mv fort.37 fort.7
        fi
        if (test -r fort.38) then
		mv fort.8 fort.8~
		mv fort.38 fort.8
		echo " rl: Relabeling finished."
        fi
fi
