#! /usr/bin/env python

import sys
import os
sys.path.append(os.path.join(os.environ["AUTO_DIR"],"python"))
from AUTOCommands import commandSubtractBranches

# This is the Python syntax for making a script runnable
if __name__ == '__main__':
    point = 1
    branch = 1
    if len(sys.argv) > 4:
        branch = int(sys.argv[4])
        if len(sys.argv) > 5:
            point = int(sys.argv[5])
    sub = commandSubtractBranches(sys.argv[1],sys.argv[2],sys.argv[3],
                                  branch=branch,point=point)
    sub()
