!------ --------------
! these are the AUTO constants, *exactly* as given in the fort.2 or c. file
! don't use this module from any parallellized function (FUNI and ICNI).
MODULE AUTO_CONSTANTS

  IMPLICIT NONE
  INTEGER NPARX,NIAP,NRAP
  INCLUDE 'auto.h'

  INTEGER NDIM,IPS,IRS,ILP
  INTEGER,ALLOCATABLE :: ICU(:)
  INTEGER NTST,NCOL,IAD,ISP,ISW,IPLT,NBC,NINT
  INTEGER NMX
  DOUBLE PRECISION RL0,RL1,A0,A1
  INTEGER NPR,MXBF,IID,ITMX,ITNW,NWTN,JAC
  DOUBLE PRECISION EPSL,EPSU,EPSS
  DOUBLE PRECISION DS,DSMIN,DSMAX
  INTEGER IADS
  TYPE INDEXVAR
     INTEGER INDEX
     DOUBLE PRECISION VAR
  END TYPE INDEXVAR  
  TYPE(INDEXVAR),ALLOCATABLE :: IVTHL(:),IVTHU(:),IVUZR(:)

  CHARACTER(13), DIMENSION(:), ALLOCATABLE :: UNAMES, PARNAMES
  CHARACTER(256) :: EFILE, SFILE, SVFILE, DATFILE

! HomCont comstants:
  INTEGER ITWIST,ISTART,IEQUIB,NFIXED,NPSI,NUNSTAB,NSTAB,NREV
!     This common block is also used by demos: don't remove it!!
!
  COMMON /BLHOM/ ITWIST,ISTART,IEQUIB,NFIXED,NPSI,NUNSTAB,NSTAB,NREV
  INTEGER, ALLOCATABLE :: IREV(:),IPSI(:),IFIXED(:)

END MODULE AUTO_CONSTANTS
