! interfaces to use instead of EXTERNAL for type checking

      INTERFACE

         SUBROUTINE FUNI(IAP,NDIM,U,UOLD,ICP,PAR,IJAC,F,DFDU,DFDP)
         INTEGER, INTENT(IN) :: IAP(*),ICP(*),NDIM,IJAC
         DOUBLE PRECISION, INTENT(IN) :: UOLD(NDIM)
         DOUBLE PRECISION, INTENT(INOUT) :: U(NDIM),PAR(*)
         DOUBLE PRECISION, INTENT(OUT) :: F(NDIM)
         DOUBLE PRECISION, INTENT(INOUT) :: DFDU(NDIM,NDIM),DFDP(NDIM,*)
         END SUBROUTINE FUNI

         SUBROUTINE BCNI(IAP,NDIM,PAR,ICP,NBC,U0,U1,F,IJAC,DBC)
         INTEGER, INTENT(IN) :: IAP(*),NDIM,ICP(*),NBC,IJAC
         DOUBLE PRECISION, INTENT(INOUT) :: U0(NDIM),U1(NDIM),PAR(*)
         DOUBLE PRECISION, INTENT(OUT) :: F(NBC)
         DOUBLE PRECISION, INTENT(INOUT) :: DBC(NBC,*)
         END SUBROUTINE BCNI

         SUBROUTINE ICNI(IAP,NDIM,PAR,ICP,NINT,U,UOLD,UDOT,UPOLD,F,IJ,D)
         INTEGER, INTENT(IN) :: IAP(*),ICP(*),NDIM,NINT,IJ
         DOUBLE PRECISION, INTENT(IN) :: UOLD(NDIM),UDOT(NDIM)
         DOUBLE PRECISION, INTENT(IN) :: UPOLD(NDIM)
         DOUBLE PRECISION, INTENT(INOUT) :: U(NDIM),PAR(*)
         DOUBLE PRECISION, INTENT(OUT) :: F(NINT)
         DOUBLE PRECISION, INTENT(INOUT) :: D(NINT,*)
         END SUBROUTINE ICNI

         SUBROUTINE STPNBVI(IAP,PAR,ICP,NTSR,NCOLRS,RLD,UPS,UDOPS,TM,ND)
         INTEGER, INTENT(INOUT) :: IAP(*)
         INTEGER, INTENT(IN) :: ICP(*)
         INTEGER, INTENT(INOUT) :: NTSR,NCOLRS
         INTEGER, INTENT(OUT) :: ND
         DOUBLE PRECISION, INTENT(OUT) :: PAR(*),RLD(*)
         DOUBLE PRECISION, INTENT(OUT) :: UPS(IAP(1),0:*)
         DOUBLE PRECISION, INTENT(OUT) :: UDOPS(IAP(1),0:*),TM(0:*)
         END SUBROUTINE STPNBVI

         SUBROUTINE STPNAEI(IAP,PAR,ICP,U,UDOT,NODIR)
         INTEGER, INTENT(INOUT) :: IAP(*)
         INTEGER, INTENT(IN) :: ICP(*)
         INTEGER, INTENT(OUT) :: NODIR
         DOUBLE PRECISION, INTENT(OUT) :: PAR(*),U(*),UDOT(*)
         END SUBROUTINE STPNAEI

         SUBROUTINE PVLI(IAP,ICP,UPS,NDIM,PAR)
         INTEGER, INTENT(IN) :: IAP(*),ICP(*),NDIM
         DOUBLE PRECISION, INTENT(IN) :: UPS(NDIM,0:*)
         DOUBLE PRECISION, INTENT(INOUT) :: PAR(*)
         END SUBROUTINE PVLI

      END INTERFACE
